image: atlassian/default-image:3

pipelines:
  branches:
    develop:
      - parallel:
        - step:
            name: 'Build Docker Image'
            caches:
              - gradle
            script:
              - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
              - docker build --pull --rm -f "Dockerfile" -t spyrosmoux/devops-backend:latest "."
              - docker push spyrosmoux/devops-backend:latest
            services:
              - docker
        - step:
            name: 'Security scan'
            script:
              - pipe: atlassian/git-secrets-scan:0.4.3